print(2+3)
print("hello world")
print("python_with_ammar")
print('what is your name')
print("what is your name")
print('''what is your name''')     
print("what's your name")
print("what's yourrrrr name")
print(  "what's your name"  )
print(  "what's your name")
print("what's your name    ?")
print(  "    what's your name"  )